# Generated by Django 4.1.7 on 2023-09-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Laptops', 'Laptops'), ('Arts', 'Arts'), ('Food', 'Food'), ('Home', 'Home'), ('Kitchen', 'Kitchen'), ('Health', 'Health'), ('Phones', 'Phones'), ('Fashion', 'Fashion'), ('Gaming', 'Gaming')], max_length=30),
        ),
    ]
