name: Django Github Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.11.0] # Change to your Python version

    steps:
      - uses: actions/checkout@v3
      - name: Set Python Version ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 .
      # - name: Run migrations
      #   run: |
      #     python manage.py migrate
      # - name: Runing the tests
      #   run: |
      #     python manage.py test
  
#   deploy:
#     runs-on: ubuntu-latest
#     name: deploy our django application to digital ocean
#     needs: [build]
#     steps:
#        - name: Checkout code
#          uses: actions/checkout@v2

#        - name: DigitalOcean App Platform deployment
#          uses: digitalocean/app_action@v1.1.5 # This is the action
#          with:
#             app_name: seashell-app # Change seashell-app to our Digital Ocean app name
#             token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} # Set DIGITALOCEAN_ACCESS_TOKEN in Repository secrets
#             # branch: "master"